import {MatGridListModule,
        MatButtonModule, 
        MatCheckboxModule, 
        MatRadioModule,
        MatIconModule, 
        MatTabsModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatFormFieldModule,
        MatInputModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatSelectModule,
        MatTableModule,
        MatSortModule,
        MatPaginatorModule
        } from '@angular/material';
import {NgModule } from '@angular/core';
@NgModule({
  imports: [MatGridListModule,
            MatButtonModule, 
            MatCheckboxModule,
            MatRadioModule,
            MatIconModule,
            MatTabsModule,
            MatSidenavModule,
            MatToolbarModule,
            MatListModule,
            MatFormFieldModule,
            MatInputModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatSelectModule,
            MatTableModule,
            MatSortModule,
            MatPaginatorModule
        ],
  exports: [MatGridListModule,
            MatButtonModule, 
            MatCheckboxModule,
            MatRadioModule,
            MatIconModule,
            MatTabsModule,
            MatSidenavModule,
            MatToolbarModule,
            MatListModule,
            MatFormFieldModule,
            MatInputModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatSelectModule,
            MatTableModule,
            MatSortModule,
            MatPaginatorModule
        ],
})export class MaterialModule {}